version: '3.4'

services:
  qodo2api:
    image: deanxv/qodo2api:latest
    container_name: qodo2api
    restart: always
    ports:
      - "10022:10022"
    volumes:
      - ./data:/app/qodo2api/data
    environment:
      - QD_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai