version: '3.4'

services:
  qodo2api:
    image: deanxv/qodo2api:latest
    container_name: qodo2api
    restart: always
    ports:
      - "10022:10022"
    volumes:
      - ./data:/app/qodo2api/data
    environment:
      - QD_COOKIE=AIzaSyCMMynYm5VRHj1NOwkfWinX-HYsFArdUbk=AMf-vBx-qgjj35ifQPoQdFDv47VJOo2YUqbhgNukxLNGaSTE6BhMVsJcvj588Ioa9HCD7FT9t57pBE4iAvPurc5G0W7fipCC3SRME92csXV4I4KSKcm_Zg8LMzEanueK9SKR-T-aI9RmUaKoQvuLAGmaJHIA2-Zo9649fAg7ZEDB5nhWMZrcXolxqGA06l8gDMpneRj-JnYH
      - API_SECRET=123456
      - TZ=Asia/Shanghai
